
#    Copyright 2018 Tech Bureau, Corp
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http:#www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.

version: '2'
services:
  ######  dynamic configuration  ###########

  generate-raw-addresses:
    image: techbureau/catapult-tools:gcc-0.5.0.1
    command: bash -c "/bin-mount/generate-raw-addresses-if-needed 50 /addresses/raw-addresses.txt /addresses/addresses.yaml"
    volumes:
    - ../../bin/bash:/bin-mount
    - ../../build/generated-addresses:/addresses:rw
    - ../../build/state:/state:rw

  store-addresses:
    build: dockerfiles/ruby-alpine
    command: ash -c "/bin-mount/wait /addresses/raw-addresses.txt && /ruby/bin/store-addresses-if-needed.rb /addresses/raw-addresses.txt /addresses/addresses.yaml"
    volumes:
    - ../../bin/ash:/bin-mount
    - ../../ruby:/ruby
    - ../../build/generated-addresses:/addresses:rw

  setup-network:
    build: dockerfiles/ruby-alpine
    command: ash -c "/bin-mount/wait /addresses/addresses.yaml && /ruby/bin/generate-and-write-configurations.rb /addresses/addresses.yaml /config-build /nemesis && touch /state/configs-generated"
    volumes:
    - ../../bin/ash:/bin-mount
    - ../../ruby:/ruby
    - ../../build/generated-addresses:/addresses
    - ../../build/catapult-config:/config-build
    - ../../build/nemesis:/nemesis:rw
    - ../../build/state:/state:rw

  ###### running services ###########

  db:
    image: mongo
    command: bash -c "mongod --dbpath=/dbdata --bind_ip=db"
    stop_signal: SIGINT
    volumes:
    - ../../data/mongo:/dbdata:rw
    - ../../bin/bash:/bin-mount

  init-db:
    image: mongo
    command:  bash -c "/bin/bash /userconfig/mongors.sh"
    volumes:
    - ../../data/mongo:/dbdata:rw
    - ../../static-config/mongo/:/userconfig/:ro
    - ../../bin/bash:/bin-mount
    depends_on:
    - db

  rest-gateway:
    image: techbureau/catapult-rest-server:1.0.16
    command: ash -c "/bin-mount/wait /state/configs-generated && npm start resources/rest.json /userconfig/rest.json"
    stop_signal: SIGINT
    ports:
    - "3000:3000"
    volumes:
    - ../../build/catapult-config/rest-gateway-0/userconfig/:/userconfig/
    - ../../bin/ash:/bin-mount
    - ../../build/state:/state
    depends_on:
    - init-db
    - setup-network

  peer-node-0-nemgen:
    build: dockerfiles/nemgen
    command: bash -c "/bin-mount/wait /state/configs-generated && /bin/bash /userconfig/nemgen.sh && touch /state/peer-node-0-nemgen"
    stop_signal: SIGINT
    volumes:
    - ../../build/catapult-config/peer-node-0/userconfig/resources/:/userconfig/resources/
    - ../../build/nemesis/:/nemesis
    - ../../data/peer-node-0:/data:rw
    - ../../bin/bash:/bin-mount
    - ../../build/state:/state:rw
    depends_on:
    - setup-network

  peer-node-0:
    build: dockerfiles/catapult
    command: bash -c "/bin-mount/wait /state/peer-node-0-nemgen && /bin/bash /userconfig/startServer.sh"
    stop_signal: SIGINT
    ports:
    - "7900:7900"
    volumes:
    - ../../build/catapult-config/peer-node-0/userconfig/resources/:/userconfig/resources/
    - ../../data/peer-node-0:/data:rw
    - ../../bin/bash:/bin-mount
    - ../../build/state:/state
    depends_on:
    - setup-network
    - peer-node-0-nemgen

# removed peer-node-1 for nf-testnet nodes
#  peer-node-1-nemgen:
#    build: dockerfiles/nemgen
#    command: bash -c "/bin-mount/wait /state/configs-generated && /bin/bash /userconfig/nemgen.sh && touch /state/peer-node-1-nemgen"
#    stop_signal: SIGINT
#    volumes:
#    - ../../build/catapult-config/peer-node-1/userconfig/resources/:/userconfig/resources/
#    - ../../build/nemesis/:/nemesis
#    - ../../data/peer-node-1:/data:rw
#    - ../../bin/bash:/bin-mount
#    - ../../build/state:/state:rw
#    depends_on:
#    - setup-network

#  peer-node-1:
#    build: dockerfiles/catapult
#    command: bash -c "/bin-mount/wait /state/peer-node-1-nemgen && /bin/bash /userconfig/startServer.sh"
#    stop_signal: SIGINT
#    volumes:
#    - ../../build/catapult-config/peer-node-1/userconfig/resources/:/userconfig/resources/
#    - ../../data/peer-node-1:/data:rw
#    - ../../bin/bash:/bin-mount
#    - ../../build/state:/state
#    depends_on:
#    - setup-network
#    - peer-node-1-nemgen

  api-node-0-nemgen:
    build: dockerfiles/nemgen
    command: bash -c "/bin-mount/wait /state/configs-generated && /bin/bash /userconfig/nemgen.sh && touch /state/api-node-0-nemgen"
    stop_signal: SIGINT
    volumes:
    - ../../build/catapult-config/api-node-0/userconfig/resources/:/userconfig/resources/
    - ../../build/nemesis/:/nemesis
    - ../../data/api-node-0:/data:rw
    - ../../bin/bash:/bin-mount
    - ../../build/state:/state:rw
    depends_on:
    - setup-network

  api-node-0:
    build: dockerfiles/catapult
    command: bash -c "/bin-mount/wait /state/api-node-0-nemgen && /bin-mount/wait /state/api-node-0-broker && /bin/bash /userconfig/startApiServer.sh"
    stop_signal: SIGINT
    ports:
    - "7910:7910"
    volumes:
    - ../../build/catapult-config/api-node-0/userconfig/resources/:/userconfig/resources/
    - ../../data/api-node-0:/data:rw
    - ../../bin/bash:/bin-mount
    - ../../build/state:/state
    depends_on:
    - setup-network
    - api-node-0-nemgen
    - api-node-broker-0

  api-node-broker-0:
    build: dockerfiles/catapult
    command: bash -c "/bin-mount/wait /state/api-node-0-nemgen && /bin/bash /userconfig/startBroker.sh"
    stop_signal: SIGINT
    volumes:
    - ../../build/catapult-config/api-node-0/userconfig/resources/:/userconfig/resources/
    - ../../data/api-node-0:/data:rw
    - ../../bin/bash:/bin-mount
    - ../../build/state:/state
