
#    Copyright 2018 Tech Bureau, Corp
# 
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
# 
#        http:#www.apache.org/licenses/LICENSE-2.0
# 
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.

version: '3'

services:
  ######  dynamic configuration  ###########
  generate-raw-addresses:
    image: techbureau/catapult-tools-private:gcc-master-8ff8de46c0
    command: bash -c "/bin-mount/generate-raw-addresses-if-needed 53 /addresses/raw-addresses.txt /addresses/addresses.yaml"
    volumes:
    - ./bin/bash:/bin-mount
    - ./build/generated-addresses:/addresses:rw
    - ./build/state:/state:rw

  store-addresses:
    build:
      context: ./ruby
      dockerfile: Dockerfile-dev
    command: bash -c "sleep infinity"
#    command: bash -c "/bin-mount/wait /addresses/raw-addresses.txt && /usr/app/bin/store-addresses-if-needed.rb /addresses/raw-addresses.txt /addresses/addresses.yaml 53"
    volumes:
    - ./bin/bash:/bin-mount
    - ./ruby:/usr/app
    - ./build/generated-addresses:/addresses:rw

  setup-network:
    build:
      context: ./ruby
      dockerfile: Dockerfile-dev
    command: bash -c "sleep infinity"
#    command: bash -c "/bin-mount/wait /addresses/addresses.yaml && /usr/app/bin/generate-and-write-configurations.rb /addresses/addresses.yaml /config-build /nemesis && touch /state/configs-generated"
    volumes:
    - ./bin/bash:/bin-mount
    - ./ruby:/usr/app
    - ./build/generated-addresses:/addresses
    - ./build/catapult-config:/config-build
    - ./build/nemesis:/nemesis:rw
    - ./build/state:/state:rw

  peer-node-0-nemgen:
    build: cmds/bootstrap/dockerfiles/nemgen
    command: bash -c "sleep infinity"
#    command: bash -c "/bin-mount/wait /state/configs-generated && /bin/bash /userconfig/nemgen.sh && touch /state/peer-node-0-nemgen"
    stop_signal: SIGINT
    volumes:
    - ./build/catapult-config/peer-node-0/userconfig/resources/:/userconfig/resources/
    - ./build/nemesis/:/nemesis
    - ./data/peer-node-0:/data:rw
    - ./bin/bash:/bin-mount
    - ./build/state:/state:rw
    depends_on:
    - setup-network
